steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/radar-mercado-public/radar-mercado-publico', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/radar-mercado-public/radar-mercado-publico']
images:
  - 'gcr.io/radar-mercado-public/radar-mercado-publico'
